NullPointerException: Attempt to read from field  'int android.net.wifi.ScanResult.level' on a null  object reference
   This bug is due to such a case: The first scan
   result belong to a network which is disabled
   temporarily or permanently

   Also clean the code remove dsiabled network since it is useless.

BUG=26576928

Change-Id: Id4f32f6f85df06659279a363906b63becceb6f76